### ISSUE TITLE
23 and me: Need to include symbols in the SDK package

### ISSUE THREAD

**Issue by JayLVouched** [vouched/vouched-ios#24]
Re https://vouched-id.slack.com/archives/C05JN0DAS3D/p1695838397993699?thread_ts=1695242245.427869&cid=C05JN0DAS3D

We should generate and package the symbol libraries necessary for our customrer debug the iOS SDK when crashes occur.

**Comment by imrank1** [comment]
@JayLVouched Looks like we closed this out in the thread with 23andMe. Feel free to comment and reopen if thats not true
