### ISSUE TITLE
All `JobError` properties are private.

### ISSUE THREAD

**Issue by ottosuess** [vouched/vouched-ios#3]
The swift interface of `JobError` looks like this:

```
public struct JobError : Swift.Codable {
  public func encode(to encoder: Swift.Encoder) throws
  public init(from decoder: Swift.Decoder) throws
}
```

Would be helpful to get access to `type` and `message`.

**Comment by JayLVouched** [comment]
@ottosuess 
We will be releasing 0.9.5 of the SDH in the next week or two, we'll be sure to incude that

**Comment by JayLVouched** [comment]
v1.0.0 release addressed this issue
