### ISSUE TITLE
Job links in Readme are broken

### ISSUE THREAD

**Issue by ottosuess** [vouched/vouched-ios#4]
All job links in readme just lead to https://docs.vouched.id/#tag/job-model.
That site does not contain any information about the Job model.

**Comment by josh-vouched** [comment]
Thanks for letting us know! We switched to a new docs site and now the link structure changed. The job model can be found by clicking the 200 response on this page: https://docs.vouched.id/reference/findjobs. I will update the readme as well.

![Screen Shot 2022-01-06 at 9 37 03 AM](https://user-images.githubusercontent.com/93531894/148426045-7ddaf469-9862-4da4-96c6-6cf099ea6106.png)
